### PR TITLE
[RFR] Repository skeleton

### PR DESCRIPTION
**Pull request by abrugaro**
This commit includes the structure of the project, config files, readme, and minimum viable test to ensure that the code works as expected.

### CODE REVIEW

**Review by sshveta — APPROVED** [review]
Looks Good @abrugaro

**Comment by mguetta1** [comment]
@abrugaro Looks like `applications` directory should be under `data`, it does not contain any fixtures
Other than that, looks good to me

**Comment by sshveta** [comment]
> @abrugaro Looks like `applications` directory should be under `data`, it does not contain any fixtures Other than that, looks good to me

Yeah applications can be moved under data . We don't need binary applications for CLI testing though , right @abrugaro . Can we remove them ?

**Comment by abrugaro** [comment]
> > @abrugaro Looks like `applications` directory should be under `data`, it does not contain any fixtures Other than that, looks good to me
> 
> Yeah applications can be moved under data . We don't need binary applications for CLI testing though , right @abrugaro . Can we remove them ?

We DO need binary applications for CLI testing. kantra analyzes them. I'll move them to the `data` folder in my next PR

**Comment by sshveta** [comment]
> > > @abrugaro Looks like `applications` directory should be under `data`, it does not contain any fixtures Other than that, looks good to me
> > 
> > 
> > Yeah applications can be moved under data . We don't need binary applications for CLI testing though , right @abrugaro . Can we remove them ?
> 
> We DO need binary applications for CLI testing. kantra analyzes them. I'll move them to the `data` folder in my next PR

Okay yeah only zip files not allowed .Other binaries are accepted.

**Pull request merged**
